image: Visual Studio 2019
configuration:
- Debug
- Debug_DLL
- Release
- Release_DLL

platform:
- x86
- x64

environment:
  matrix:
  - BUILD_SYSTEM: MSVC
  - BUILD_SYSTEM: CMAKE
build:
  project: Fresponze.sln
  parallel: true
  verbosity: minimal
after_build:
  - if "%BUILD_SYSTEM%" == "MSVC" (
      7z a fresponze.zip build\%PLATFORM%\%CONFIGURATION%\*.lib build\%PLATFORM%\%CONFIGURATION%\*.dll build\%PLATFORM%\%CONFIGURATION%\*.pdb inc\*.h
    )

artifacts:
- path: fresponze.zip
